-- Seed site_details with consortium site data
-- Run via: turso db shell clif-consortium < seed-site-details.sql
-- Idempotent: uses ON CONFLICT to upsert

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of Chicago', 'University of Chicago', 'Academic', 1, 146, 'CRDW', '2018-2024', '2018-2024', 1, 1, 1, 'Biological Sciences Division/University of Chicago Medical Center IRB', 'IRB20-1823', '12/7/2020', 'approval', 'all acute care = any inpatient + ED encounters', 'can pull')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Rush University', 'Rush University', 'Academic', 1, 112, 'Caboodle, Clarity', '2018-2024', '2018-2024', 1, 1, 1, NULL, '20082408-IRB01', NULL, NULL, 'all acute care', 'can pull')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Northwestern University', 'Northwestern University', 'Academic & community', 10, 280, 'EDW', '2018-2024', '2018-2024', 1, 1, 1, 'x', 'STU00223260', NULL, 'approval', 'admissions with an ICU stay', 'H&P and progress')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Oregon Health & Science University', 'Oregon Health & Science University', 'Academic & community', 2, 90, 'CRDW', '2016-2024', '2016-2024', 1, 1, 1, NULL, 'STUDY00025188', '12/5/2022', 'exempt', 'all acute care', NULL)
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of Minnesota', 'University of Minnesota', 'Academic & community', 13, 159, 'Clarity', '2011-2024', '2011-2024', 1, 1, 1, 'UMN IRB', 'STUDY00014815', '1/19/2022', 'approval', 'all acute care', NULL)
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Johns Hopkins University', 'Johns Hopkins University', 'Academic & community', 9, 236, 'CRDW', 'July 2017 - Onwards', 'July 2017-Onwards', 1, 1, 1, 'Johns Hopkins School of Medicine - "Harnessing the Common Longitudinal ICU Format (CLIF) to Understand Variation in Early Critical Illness"', 'IRB00421735', NULL, 'exempt', 'Any patient who was in ICU/IMC OR on supplemental oxygen/respiratory support or SBP<90 OR vasoactives. Once meet registry criteria all encounters before/after get included', 'Not right now')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Emory University', 'Emory University', 'Academic & community', 10, NULL, 'EDW', '2022-2024', '2022-2024', 1, 1, 1, NULL, '2025P010108', '7/29/2025', 'approval', 'all acute care', 'can pull')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of Michigan', 'University of Michigan', 'Academic', 1, 179, 'RDW', '2015-2024', '2017-2024', 1, 1, 1, 'University of Michigan Medical School Institutional Review Board', 'HUM00260807', '9/16/2024', 'exempt', 'all inpatient data on admissions with an ICU stay', NULL)
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of Pennsylvania', 'University of Pennsylvania', 'Academic & community', 8, 297, 'Clarity/CIRCE', 'July 2017 - Onwards', 'July 2017 - Onwards', 1, 1, 1, NULL, 'IRB #853717', '5/16/2023', 'exempt', 'all acute care', 'can pull')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes, notes)
VALUES (lower(hex(randomblob(16))), 'University of Toronto', 'University of Toronto', 'Academic', 1, 74, 'Metavision', 'January 2017-September 2021', 'January 2017-September 2021', 1, 1, 1, NULL, NULL, NULL, NULL, 'frankenstein', 'all notes', 'ER and Ward data are limited')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes, notes=excluded.notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of California San Francisco', 'University of California San Francisco', 'Academic', 5, 102, 'CRDW', '2011 - Onwards', '2011 - Onwards', 1, 1, 1, NULL, NULL, NULL, NULL, 'admissions with an ICU stay', 'can pull as needed')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'University of Colorado', 'University of Colorado', 'Academic & community', 19, NULL, 'Caboodle, Clarity / CLIO', '2014 - onwards', '2014 - onwards', 1, 1, 1, 'Colorado Multiple Institutional Review Board (COMIRB)', '#25-0761', '6/24/2025', 'exempt', 'all acute care', 'can pull as needed')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;

INSERT INTO site_details (id, site_name, institution, hospital_type, num_hospitals, icu_beds, data_source, source_data_date_range, clifed_date_range, has_er_data, has_icu_data, has_ward_data, irb_name, irb_number, irb_approval_date, irb_approval_type, cohort_inclusion_criteria, pulled_notes)
VALUES (lower(hex(randomblob(16))), 'Harvard University', 'Harvard University', 'Academic & community', 9, NULL, 'Clarity', 'April 2015 - onwards', 'April 2015 - onwards', 1, 1, 1, 'Mass General Brigham IRB', '2025P000991', '4/30/2025', 'approval', 'all patients admitted to the hospital or died in ED', 'no')
ON CONFLICT(site_name) DO UPDATE SET
  institution=excluded.institution, hospital_type=excluded.hospital_type, num_hospitals=excluded.num_hospitals, icu_beds=excluded.icu_beds, data_source=excluded.data_source, source_data_date_range=excluded.source_data_date_range, clifed_date_range=excluded.clifed_date_range, has_er_data=excluded.has_er_data, has_icu_data=excluded.has_icu_data, has_ward_data=excluded.has_ward_data, irb_name=excluded.irb_name, irb_number=excluded.irb_number, irb_approval_date=excluded.irb_approval_date, irb_approval_type=excluded.irb_approval_type, cohort_inclusion_criteria=excluded.cohort_inclusion_criteria, pulled_notes=excluded.pulled_notes;
