name: Refresh ADT location categories

on:
  schedule:
    # Every day at 03:00 UTC
    - cron: '0 3 * * 0'
  # Allow manual trigger from the GitHub UI
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo so we can modify and push files
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need full history to push back

      # 2. Set up Node (same version you use locally / in production)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install project dependencies (including csv-parse and your script)
      - run: npm ci

      # 4. Regenerate the permissible-values comment in the DDL files
      - name: Update DDL files
        run: npm run ddl:update

      # 5. Commit & push back only if something changed
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name  "ddl-bot"
            git config user.email "ddl-bot@users.noreply.github.com"
            git add src/content/*.sql
            git commit -m "chore: refresh ADT location categories"
            git push
          else
            echo "No changes to commit."
          fi
